#!/bin/bash
INFLUXDB_INIT_PORT="$INFLUXDB_PORT"
INFLUX_CMD="influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT -execute "

# Create the timeseries database
$INFLUX_CMD "CREATE DATABASE \"$TIMESERIES_DB\""

# Create the server-agent user, and grant access.
$INFLUX_CMD "CREATE USER \"$SERVER_AGENT_USER\" WITH PASSWORD '$SERVER_AGENT_USER'"
$INFLUX_CMD "GRANT ALL ON \"$TIMESERIES_DB\" TO \"$SERVER_AGENT_USER\""

# Create the dashboard user, and grant access.
$INFLUX_CMD "CREATE USER \"$DASHBOARD_USER\" WITH PASSWORD '$DASHBOARD_USER_PASSWORD'"
$INFLUX_CMD "GRANT READ ON \"$TIMESERIES_DB\" TO \"$DASHBOARD_USER\"
